version: '3.8'

services:
  tryoutkan-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - tryoutkan-network

networks:
  tryoutkan-network:
    driver: bridge